- name: "Upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install NodeJs v12.x"
  shell: |
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt -y upgrade
    sudo apt install -y nodejs
  
- name: "Install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy files from CircleCI to server"
  copy:
    src: /root/Udapeople/backend
    dest: /home/ubuntu

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install
