- name: "Upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install node and npm" 
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2 by npm"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Copy files from CircleCI to server"
  copy:
    src: /root/cdond-c3-projectstarter/backend
    dest: /home/ubuntu

- name: "Install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 