- name: "Create Backend App Directory"
  file:
    path: /home/ubuntu/udapeople-backend-app
    state: directory

- name: "Extract Backend Artifact"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople-backend-app

- name: "Install Dependencies"
  shell: |
    cd /home/ubuntu/udapeople-backend-app
    npm install

- name: "Start Backend Service"
  become: true
  shell: |
    cd /home/ubuntu/udapeople-backend-app 
    npm install
    pm2 stop default
    pm2 start npm -- start
  register: udapeople_backend_server

- name: "Log Server Messages"
  debug:
    msg: "{{ udapeople_backend_server.stdout_lines }}"

- name: "Configure PM2 As A systemd Service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
