Description: >
  UdaPeople Backend Stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow ports 22, 3030 and 9100.
      SecurityGroupIngress:
        - IpProtocol: tcp # ssh
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp # node app
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp # prometheus
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity # security group
      ImageId: ami-0729e439b6769d6ab # ubuntu 20.04 lts
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
